### ISSUE TITLE
安装以后无法使用fish

### ISSUE THREAD

**Issue by tr15tan** [chaopeng/ph#1]
系统：kde neon 5.17.4
安装过程：

1. 全新安装`go`,安装完成后`PATH`里没有`~/go/bin`,手动在`~/.profile`里添加
```
export GOPATH=$HOME/go
export PATH=$PATH:~/go/bin
```
`echo PATH`中已经可以看到`/home/tristan/go/bin`追加在最后

2. 下载[Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack)中提供的最新版本压缩包，解压后只有4个字体文件`Hack-BoldItalic.ttf Hack-Bold.ttf Hack-Italic.ttf Hack-Regular.ttf`,并没有安装步骤里提到的字体配置文件，所以直接使用`fc-list | grep "Hack"`查看，发现已经安装有Hack字体，于是不再安装
```
/usr/share/fonts/truetype/hack/Hack-Regular.ttf: Hack:style=Regular
/usr/share/fonts/truetype/hack/Hack-Bold.ttf: Hack:style=Bold
/usr/share/fonts/truetype/hack/Hack-BoldItalic.ttf: Hack:style=Bold Italic
/usr/share/fonts/truetype/hack/Hack-Italic.ttf: Hack:style=Italic
```

3. `sudo apt install fish`安装`fish`,安装完成后可以使用`fish`

4. 使用`ph-master/install.sh`安装，输出如下（不是第一次执行，前面执行的输出没有保存）
```
?       github.com/chaopeng/ph  [no test files]
?       github.com/chaopeng/ph/cmd      [no test files]
ok      github.com/chaopeng/ph/config   (cached)
ok      github.com/chaopeng/ph/context  (cached)
?       github.com/chaopeng/ph/theme    [no test files]
ok      github.com/chaopeng/ph/theme/powerline  (cached)
ok      github.com/chaopeng/ph/theme/simple     (cached)
ok      github.com/chaopeng/ph/theme/simpleass  (cached)
?       github.com/chaopeng/ph/util     [no test files]
?       github.com/chaopeng/ph/vcs      [no test files]
ok      github.com/chaopeng/ph/vcs/git  (cached)
ok      github.com/chaopeng/ph/vcs/hg   (cached)
ph installed.
```

5. 手动创建`/home/tristan/.config/fish/functions/fish_prompt.fish`，添加
```
function fish_prompt
  set -l last_status $status
  $HOME/bin/ph prompt $last_status
end
```
保存后终端执行`fish`，输出如下
```
Welcome to fish, the friendly interactive shell
Segmentation fault
```
无法进入`fish`，删除该文件后才能使用fish

是我安装的哪里有问题吗？如果能够解决的话，我还想问一下怎么能够让`fish`显示完整路径，而不是第一个字母的缩写，谢谢

**Comment by chaopeng** [comment]
我觉得可能问题在`$HOME/bin/ph`，我改了install.sh以后，ph应该被安装在~/go/bin，你可以试试先改这个，但是我没有看到`Segmentation fault`这个错误。你先试试能不能解决。另外建议你先试试run `$HOME/go/bin/ph prompt  1`看看有没有问题，确认一下是不是ph的问题。

如果你想显示完整路径，你可以改这里https://github.com/chaopeng/ph/blob/a5c0ce8b17a6f26a5d2e0d3cd3e8a488ae3e464e/context/context.go#L67-L77

```
// 把那几行删了，改成
pathInfo.ShorternPrefix = prePath
```

我下一段时间有空，会考虑把这个加入config。

**Comment by tr15tan** [comment]
我重新创建一个虚拟机又安装了一次，并且按照README去添加`fish_prompt`，这次没有提示有`Segmentation fault`，但是又出现了另一个错误，而且`tmux`的输出也不对 
![Screenshot_20200113_161815](https://user-images.githubusercontent.com/8577890/72243296-87030280-3626-11ea-938f-c7b19136f2a0.png)

删除`fish_prompt.fish`后，能够正常使用`fish`。这个是我这里的go环境问题吗？

如果按照`pathInfo.ShorternPrefix = prePath`修改，有类型匹配问题，改成`pathInfo.ShorternPrefix = strings.Join(prePath, "/") + "/"`后，测试用例又过不了
![Screenshot_20200113_161442](https://user-images.githubusercontent.com/8577890/72243225-4f945600-3626-11ea-933d-367390738011.png)

**Comment by chaopeng** [comment]
1. fish_prompt.sh那里好像是fish版本的问题，https://github.com/fish-shell/fish-shell/issues/154
你可以改成eval $HOME/go/bin/ph prompt $last_status
2. tmux那个输出看着是正确的，这就是tmux status需要的格式
3. 你可以临时改一下testcase，让这个可以过，或者直接删除install.sh里面的`go test ./...`

**Comment by tr15tan** [comment]
确实是`fish`版本问题，我的版本是2.7.1，更新到3.0.2以后就没有报错了，而且能够成功修改文件路径显示为完整名称了。

我还有1个问题想问一下，添加`～/.tmux.conf`并且在`~/.config/fish/functions/fish_prompt.fish`追加
```
function set_status -e fish_prompt
  if [ ! -n "$TMUX" ]
    return
  end

  set -l tmuxstatus ($HOME/go/bin/ph tmux)
  tmux set -g status-left "$tmuxstatus" 1
end
```
以后，左下角没有显示目录，这个可能是哪里不对？

![Screenshot_20200114_215257](https://user-images.githubusercontent.com/8577890/72352247-ddeb0380-371c-11ea-8218-9099006ab026.png)

**Comment by chaopeng** [comment]
你是不是没有去改tmux的配置
看这一段
https://github.com/chaopeng/ph#setup-for-tmux

**Comment by tr15tan** [comment]
已经添加`~/.tmux.conf`了，并且应该是生效了，没有添加时候的样式是下面这个
![Screenshot_20200116_143514](https://user-images.githubusercontent.com/8577890/72499822-e69f1f00-386d-11ea-8335-5bd5027aa579.png)

**Comment by chaopeng** [comment]
1. 试试把`$HOME/go/bin/ph tmux` 改成`$HOME/go/bin/ph tmux 0`，`tmux set -g status-left "$tmuxstatus" 1`改成`tmux set -g status-left "$tmuxstatus"`
2. 试试执行`functions set_status` 看看fish是不是已经自动载入了这个function
3. 不要加载这个函数，去进入tmux里面，然后执行  tmux set -g status-left "aaa" ，看看是否生效
4. tmux -V 查看版本，我的是2.9

**Comment by tr15tan** [comment]
按照1修改后没有变化
按照2执行后已经自动载入
```
# Defined in /home/tristan/.config/fish/functions/fish_prompt.fish @ line 26
function set_status --on-event fish_prompt
if [ ! -n "$TMUX" ]
return
end

set -l tmuxstatus ($HOME/go/bin/ph tmux 0)
tmux set -g status-left "$tmuxstatus"
end
```
按照3执行后可以看到aaa已经被显示在左下角
以上内容都是在tmux 2.6版本上执行的，更新到2.9和3.0a之后运行tmux都会显示
```
/home/tristan/.tmux.conf:10: invalid option: window-status-current-bg[0/0]
/home/tristan/.tmux.conf:12: invalid option: window-status-current-attr
```
算了我暂时不在tmux中折腾了，终端中已经可以正常使用，谢谢回复。

**Comment by chaopeng** [comment]
tmux 2.9以后有个语法变更：你试试改成这样

```
# theme
# Set the background color dark grey
set -g status-style bg=colour240

# Show nothing on status left
set -g status-left ''
set -g status-left-length 80

# Show nothing on status right
set -g status-right ''
set -g status-justify right
set -g window-status-current-style bg=colour28,bold
set -g window-status-current-format ' #[fg=colour15]#I.#W#F '
set -g window-status-format ' #[fg=colour15]#I.#W '
```
